# agents/documentation_agent.py

import json
from typing import Dict
from model.llm_client import call_llm

SYSTEM_PROMPT = """
You are a Senior Documentation Engineer.

You will receive a JSON object as a string. It contains information about a software project:
- project_name
- summary
- goal
- features
- tech_stack
- requirements
- non_functional_requirements
- assumptions

Your task:
Generate a clean, professional README.md in **Markdown**.

Follow this structure:

# <Project Name>

## Overview
- Short summary of the project (2–4 lines)

## Goal
- What this project is trying to achieve

## Features
- Bullet list of main features

## Tech Stack
- Bullet list of technologies and tools

## Requirements
- Bullet list of functional requirements

## Non-Functional Requirements
- Bullet list (performance, scalability, security, etc.) if any

## Assumptions
- Bullet list of assumptions (if any)

## Project Structure
- This section will later be filled by another agent with the actual folder structure.
- For now, just put a placeholder text:
  "Folder structure will be auto-generated by the structure agent."

## Getting Started
- General steps: clone, install dependencies, run the project (generic, based on tech_stack if possible)

## Contribution
- Simple generic instructions on how to contribute.

Rules:
- Output MUST be valid Markdown. Do NOT wrap the whole response in ```markdown``` or any code fences.
- Do NOT include any JSON in the output.
- Do NOT mention that you are an AI.
"""

def run_documentation_agent(project_info: Dict) -> str:
    """
    Takes parsed project info (dict from parser_agent)
    and returns a README.md string in Markdown format.
    """
    payload = json.dumps(project_info, indent=2)
    readme_md = call_llm(SYSTEM_PROMPT, payload)
    return readme_md
